version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: web-project-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: